# Generated by Django 3.2.6 on 2021-08-07 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_query', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gcdextractedstorycredit',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='gcdstorycredit',
            options={'managed': True},
        ),
    ]
