# Generated by Django 3.2.6 on 2021-08-07 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_query', '0002_auto_20210807_2141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gcdextractedstorycredit',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='gcdstorycredit',
            options={'managed': False},
        ),
    ]
