# Generated by Django 3.1.7 on 2021-06-05 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_query', '0002_auto_20210310_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='GcdExtractedStoryCredit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField()),
                ('deleted', models.IntegerField()),
                ('is_credited', models.IntegerField()),
                ('is_signed', models.IntegerField()),
                ('uncertain', models.IntegerField()),
                ('signed_as', models.CharField(max_length=255)),
                ('credited_as', models.CharField(max_length=255)),
                ('credit_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'm_story_credit',
                'managed': False,
            },
        ),
    ]
