# Generated by Django 3.2.6 on 2021-08-31 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_query', '0003_auto_20210807_2156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gcdcharacter',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='gcdcharacterappearance',
            options={'managed': False},
        ),
    ]
