# Generated by Django 3.2.5 on 2021-07-22 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_query', '0004_djangocontenttype_djangomigrations'),
    ]

    operations = [
        migrations.CreateModel(
            name='GcdCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('alter_ego', models.TextField(null=True)),
                ('publisher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='db_query.gcdpublisher')),
            ],
            options={
                'db_table': 'm_character',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GcdCharacterAppearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(null=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_query.gcdcharacter')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_query.gcdstory')),
                ('notes', models.TextField(null=True)),
                ('membership', models.TextField(null=True)),
            ],
            options={
                'db_table': 'm_character_appearance',
                'managed': True,
            },
        ),
    ]
