# Generated by Django 3.2.5 on 2021-07-24 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_query', '0005_gcdcharacter_gcdcharacterappearance_squashed_0010_auto_20210722_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gcdcharacter',
            name='alter_ego',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='gcdcharacter',
            index=models.Index(fields=['name', 'alter_ego'], name='m_character_name_e482d3_idx'),
        ),
    ]
