# Generated by Django 3.2.5 on 2021-07-21 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_query', '0005_gcdcharacter_gcdcharacterappearance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gcdcharacter',
            name='alter_ego',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gcdcharacterappearance',
            name='details',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
