# Generated by Django 3.2.5 on 2021-07-21 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_query', '0006_auto_20210721_0420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gcdcharacter',
            name='alter_ego',
            field=models.TextField(null=True),
        ),
    ]
