# Generated by Django 3.2.5 on 2021-07-21 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_query', '0007_alter_gcdcharacter_alter_ego'),
    ]

    operations = [
        migrations.AddField(
            model_name='gcdcharacter',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='db_query.gcdpublisher'),
        ),
        migrations.AlterField(
            model_name='gcdcharacterappearance',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_query.gcdcharacter'),
        ),
        migrations.AlterField(
            model_name='gcdcharacterappearance',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_query.gcdstory'),
        ),
    ]
