# Generated by Django 3.2.5 on 2021-07-22 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_query', '0008_auto_20210721_0621'),
    ]

    operations = [
        migrations.AddField(
            model_name='gcdcharacter',
            name='membership',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='gcdcharacterappearance',
            name='notes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='gcdcharacterappearance',
            name='details',
            field=models.TextField(null=True),
        ),
    ]
